language: java

jdk:
  - oraclejdk8

script:
  - mvn clean package

# we don't need sudo, this allows container-based builds ...
sudo: false

# ... which allows caching of .m2 and makes builds faster
cache:
  directories:
    - $HOME/.m2
